export const designPackages = [
  {
    id: "starter",
    title: "Starter Pack",
    originalPrice: "7,999/-",
    price: 4999,
    discountPercent: 38, 
    currency: "INR",
    highlight: false,
    description: "Perfect for indie builders & early startups",
    includes: {
      templates: 3,
      bonus: 1,
    },
    templates: [
      {
        id: "algora",
        name: "Algora",
        videoUrl: "https://res.cloudinary.com/dibdv4bv4/video/upload/v1770196798/algora_gbqxgg.mp4",
        downloadUrl: "/downloads/algora.zip",
      },
      {
        id: "isochrome",
        name: "Isochrome",
        videoUrl: "https://res.cloudinary.com/dibdv4bv4/video/upload/v1770196790/isochrome_lytlmq.mp4",
        downloadUrl: "/downloads/isochrome.zip",
      },
      {
        id: "nico-palmer",
        name: "Nico Palmer",
        videoUrl: "https://res.cloudinary.com/dibdv4bv4/video/upload/v1770196830/nico-palmer_rt9i0d.mp4",
        downloadUrl: "/downloads/nico-palmer.zip",
      },
    ],
    bonusTemplates: [
      {
        id: "hero-sections",
        name: "Hero Sections Collection",
        videoUrl: "/videos/hero-sections.mp4",
        downloadUrl: "/downloads/hero-sections.zip",
      },
    ],
  },

  {
    id: "pro",
    title: "Pro Pack",
    originalPrice: "14,999",
    price: 9999,
    discountPercent: 33,
    currency: "INR",
    highlight: true,
    description: "Best for agencies & serious founders",
    includes: {
      templates: 8,
      bonus: 2,
    },
    templates: [
      {
        id: "algora",
        name: "Algora",
        videoUrl: "https://res.cloudinary.com/dibdv4bv4/video/upload/v1770196798/algora_gbqxgg.mp4",
        downloadUrl: "/downloads/algora.zip",
      },
      {
        id: "isochrome",
        name: "Isochrome",
        videoUrl: "https://res.cloudinary.com/dibdv4bv4/video/upload/v1770196790/isochrome_lytlmq.mp4",
        downloadUrl: "/downloads/isochrome.zip",
      },
      {
        id: "nico-palmer",
        name: "Nico Palmer",
        videoUrl: "https://res.cloudinary.com/dibdv4bv4/video/upload/v1770196830/nico-palmer_rt9i0d.mp4",
        downloadUrl: "/downloads/nico-palmer.zip",
      },
      {
        id: "format-achieve",
        name: "Format Achieve",
        videoUrl: "https://res.cloudinary.com/dibdv4bv4/video/upload/v1770196792/format-achieve_siqvr4.mp4",
        downloadUrl: "/downloads/format-achieve.zip",
      },
      {
        id: "otis-valen",
        name: "Otis Valen",
        videoUrl: "https://res.cloudinary.com/dibdv4bv4/video/upload/v1770196853/otis-valen_p4mz1p.mp4",
        downloadUrl: "/downloads/otis-valen.zip",
      },
      {
        id: "wu-wei",
        name: "Wu Wei",
        videoUrl: "https://res.cloudinary.com/dibdv4bv4/video/upload/v1770196836/wu-wei_og3qa8.mp4",
        downloadUrl: "/downloads/wu-wei.zip",
      },
      {
        id: "juno-watts",
        name: "Juno Watts",
        videoUrl: "https://res.cloudinary.com/dibdv4bv4/video/upload/v1770196806/juno-watts_dnrwex.mp4",
        downloadUrl: "/downloads/juno-watts.zip",
      },
      {
        id: "terrene",
        name: "Terrene",
        videoUrl: "https://res.cloudinary.com/dibdv4bv4/video/upload/v1770196839/terrene_cftfap.mp4",
        downloadUrl: "/downloads/terrene.zip",
      },
    ],
    bonusTemplates: [
      {
        id: "hero-sections-pro",
        name: "Hero Sections Pro",
        videoUrl: "/videos/hero-sections-pro.mp4",
        downloadUrl: "/downloads/hero-sections-pro.zip",
      },
      {
        id: "footer-pack",
        name: "Footer Variations Pack",
        videoUrl: "/videos/footer-pack.mp4",
        downloadUrl: "/downloads/footer-pack.zip",
      },
    ],
  },

  {
    id: "ultimate",
    title: "Ultimate Pack",
    originalPrice: "24,999",
    price: 14999,
    discountPercent: 40,
    currency: "INR",
    highlight: false,
    description: "Everything we’ve ever built — and future updates",
    includes: {
      templates: 15,
      bonus: 3,
    },
    templates: [
      {
        id: "algora",
        name: "Algora",
        videoUrl: "https://res.cloudinary.com/dibdv4bv4/video/upload/v1770196798/algora_gbqxgg.mp4",
        downloadUrl: "/downloads/algora.zip",
      },
      {
        id: "isochrome",
        name: "Isochrome",
        videoUrl: "https://res.cloudinary.com/dibdv4bv4/video/upload/v1770196790/isochrome_lytlmq.mp4",
        downloadUrl: "/downloads/isochrome.zip",
      },
      {
        id: "nico-palmer",
        name: "Nico Palmer",
        videoUrl: "https://res.cloudinary.com/dibdv4bv4/video/upload/v1770196830/nico-palmer_rt9i0d.mp4",
        downloadUrl: "/downloads/nico-palmer.zip",
      },
      {
        id: "format-achieve",
        name: "Format Achieve",
        videoUrl: "https://res.cloudinary.com/dibdv4bv4/video/upload/v1770196792/format-achieve_siqvr4.mp4",
        downloadUrl: "/downloads/format-achieve.zip",
      },
      {
        id: "otis-valen",
        name: "Otis Valen",
        videoUrl: "https://res.cloudinary.com/dibdv4bv4/video/upload/v1770196853/otis-valen_p4mz1p.mp4",
        downloadUrl: "/downloads/otis-valen.zip",
      },
      {
        id: "wu-wei",
        name: "Wu Wei",
        videoUrl: "https://res.cloudinary.com/dibdv4bv4/video/upload/v1770196836/wu-wei_og3qa8.mp4",
        downloadUrl: "/downloads/wu-wei.zip",
      },
      {
        id: "juno-watts",
        name: "Juno Watts",
        videoUrl: "https://res.cloudinary.com/dibdv4bv4/video/upload/v1770196806/juno-watts_dnrwex.mp4",
        downloadUrl: "/downloads/juno-watts.zip",
      },
      {
        id: "terrene",
        name: "Terrene",
        videoUrl: "https://res.cloudinary.com/dibdv4bv4/video/upload/v1770196839/terrene_cftfap.mp4",
        downloadUrl: "/downloads/terrene.zip",
      },
      {
        id: "negative-films",
        name: "Negative Films",
        videoUrl: "https://res.cloudinary.com/dibdv4bv4/video/upload/v1770196807/negative-films_gjkyza.mp4",
        downloadUrl: "/downloads/negative-films.zip",
      },
      {
        id: "polite-chaos",
        name: "Polite Chaos",
        videoUrl: "https://res.cloudinary.com/dibdv4bv4/video/upload/v1770196820/polite-chaos_gecazl.mp4",
        downloadUrl: "/downloads/polite-chaos.zip",
      },
      {
        id: "orbit-matter",
        name: "Orbit Matter",
        videoUrl: "https://res.cloudinary.com/dibdv4bv4/video/upload/v1770196828/orbit-matter_kddzdo.mp4",
        downloadUrl: "/downloads/orbit-matter.zip",
      },
      {
        id: "nrmlss",
        name: "Nrmlss",
        videoUrl: "https://res.cloudinary.com/dibdv4bv4/video/upload/v1770196803/nrmlss_znnnso.mp4",
        downloadUrl: "/downloads/nrmlss.zip",
      },
      {
        id: "deadspace",
        name: "Deadspace",
        videoUrl: "https://res.cloudinary.com/dibdv4bv4/video/upload/v1770196785/deadspace_dubb4t.mp4",
        downloadUrl: "/downloads/deadspace.zip",
      },
      {
        id: "portfolio",
        name: "Portfolio Showcase",
        videoUrl: "https://res.cloudinary.com/dibdv4bv4/video/upload/v1770188672/portfolio_rbj5p2.mp4",
        downloadUrl: "/downloads/portfolio.zip",
      },
      {
        id: "music-and-dance",
        name: "Music and Dance",
        videoUrl: "https://res.cloudinary.com/dibdv4bv4/video/upload/v1770188666/music-and-dance_hfjtwr.mp4",
        downloadUrl: "/downloads/music-and-dance.zip",
      },
    ],
    bonusTemplates: [
      {
        id: "hero-master",
        name: "Hero Sections Master Pack",
        videoUrl: "/videos/hero-master.mp4",
        downloadUrl: "/downloads/hero-master.zip",
      },
      {
        id: "cta-pack",
        name: "CTA & Conversion Sections",
        videoUrl: "/videos/cta-pack.mp4",
        downloadUrl: "/downloads/cta-pack.zip",
      },
      {
        id: "motion-presets",
        name: "GSAP & Motion Presets",
        videoUrl: "/videos/motion-presets.mp4",
        downloadUrl: "/downloads/motion-presets.zip",
      },
    ],
  },
];
