export const designPackages = [
  {
    id: "starter",
    title: "Starter Pack",
    originalPrice: "7,999/-",
    price: "4,999",
    razorpayLink: "https://rzp.io/rzp/dtO8bMm7",
    discountPercent: 38, 
    currency: "INR",
    highlight: false,
    description: "Perfect for indie builders & early startups",
    includes: {
      templates: 3,
      bonus: 1,
    },
    templates: [
      {
        id: "algora",
        name: "Algora",
        videoUrl: "/videos/algora.mp4",
        downloadUrl: "/downloads/algora.zip",
      },
      {
        id: "isochrome",
        name: "Isochrome",
        videoUrl: "/videos/isochrome.mp4",
        downloadUrl: "/downloads/isochrome.zip",
      },
      {
        id: "nico-palmer",
        name: "Nico Palmer",
        videoUrl: "/videos/nico-palmer.mp4",
        downloadUrl: "/downloads/nico-palmer.zip",
      },
    ],
    bonusTemplates: [
      {
        id: "hero-sections",
        name: "Hero Sections Collection",
        videoUrl: "/videos/hero-sections.mp4",
        downloadUrl: "/downloads/hero-sections.zip",
      },
    ],
  },

  {
    id: "pro",
    title: "Pro Pack",
    originalPrice: "14,999",
    price: "9,999",
    razorpayLink: "https://rzp.io/rzp/cYCuDlcj",
    discountPercent: 33,
    currency: "INR",
    highlight: true,
    description: "Best for agencies & serious founders",
    includes: {
      templates: 8,
      bonus: 2,
    },
    templates: [
      {
        id: "algora",
        name: "Algora",
        videoUrl: "/videos/algora.mp4",
        downloadUrl: "/downloads/algora.zip",
      },
      {
        id: "isochrome",
        name: "Isochrome",
        videoUrl: "/videos/isochrome.mp4",
        downloadUrl: "/downloads/isochrome.zip",
      },
      {
        id: "nico-palmer",
        name: "Nico Palmer",
        videoUrl: "/videos/nico-palmer.mp4",
        downloadUrl: "/downloads/nico-palmer.zip",
      },
      {
        id: "format-achieve",
        name: "Format Achieve",
        videoUrl: "/videos/format-achieve.mp4",
        downloadUrl: "/downloads/format-achieve.zip",
      },
      {
        id: "otis-valen",
        name: "Otis Valen",
        videoUrl: "/videos/otis-valen.mp4",
        downloadUrl: "/downloads/otis-valen.zip",
      },
      {
        id: "wu-wei",
        name: "Wu Wei",
        videoUrl: "/videos/wu-wei.mp4",
        downloadUrl: "/downloads/wu-wei.zip",
      },
      {
        id: "juno-watts",
        name: "Juno Watts",
        videoUrl: "/videos/juno-watts.mp4",
        downloadUrl: "/downloads/juno-watts.zip",
      },
      {
        id: "terrene",
        name: "Terrene",
        videoUrl: "/videos/terrene.mp4",
        downloadUrl: "/downloads/terrene.zip",
      },
    ],
    bonusTemplates: [
      {
        id: "hero-sections-pro",
        name: "Hero Sections Pro",
        videoUrl: "/videos/hero-sections-pro.mp4",
        downloadUrl: "/downloads/hero-sections-pro.zip",
      },
      {
        id: "footer-pack",
        name: "Footer Variations Pack",
        videoUrl: "/videos/footer-pack.mp4",
        downloadUrl: "/downloads/footer-pack.zip",
      },
    ],
  },

  {
    id: "ultimate",
    title: "Ultimate Pack",
    originalPrice: "24,999",
    price: "14,999",
    razorpayLink: "https://rzp.io/rzp/WI9tl6EO",
    discountPercent: 40,
    currency: "INR",
    highlight: false,
    description: "Everything we’ve ever built — and future updates",
    includes: {
      templates: 15,
      bonus: 3,
    },
    templates: [
      {
        id: "algora",
        name: "Algora",
        videoUrl: "/videos/algora.mp4",
        downloadUrl: "/downloads/algora.zip",
      },
      {
        id: "isochrome",
        name: "Isochrome",
        videoUrl: "/videos/isochrome.mp4",
        downloadUrl: "/downloads/isochrome.zip",
      },
      {
        id: "nico-palmer",
        name: "Nico Palmer",
        videoUrl: "/videos/nico-palmer.mp4",
        downloadUrl: "/downloads/nico-palmer.zip",
      },
      {
        id: "format-achieve",
        name: "Format Achieve",
        videoUrl: "/videos/format-achieve.mp4",
        downloadUrl: "/downloads/format-achieve.zip",
      },
      {
        id: "otis-valen",
        name: "Otis Valen",
        videoUrl: "/videos/otis-valen.mp4",
        downloadUrl: "/downloads/otis-valen.zip",
      },
      {
        id: "wu-wei",
        name: "Wu Wei",
        videoUrl: "/videos/wu-wei.mp4",
        downloadUrl: "/downloads/wu-wei.zip",
      },
      {
        id: "juno-watts",
        name: "Juno Watts",
        videoUrl: "/videos/juno-watts.mp4",
        downloadUrl: "/downloads/juno-watts.zip",
      },
      {
        id: "terrene",
        name: "Terrene",
        videoUrl: "/videos/terrene.mp4",
        downloadUrl: "/downloads/terrene.zip",
      },
      {
        id: "negative-films",
        name: "Negative Films",
        videoUrl: "/videos/negative-films.mp4",
        downloadUrl: "/downloads/negative-films.zip",
      },
      {
        id: "polite-chaos",
        name: "Polite Chaos",
        videoUrl: "/videos/polite-chaos.mp4",
        downloadUrl: "/downloads/polite-chaos.zip",
      },
      {
        id: "orbit-matter",
        name: "Orbit Matter",
        videoUrl: "/videos/orbit-matter.mp4",
        downloadUrl: "/downloads/orbit-matter.zip",
      },
      {
        id: "nrmlss",
        name: "Nrmlss",
        videoUrl: "/videos/nrmlss.mp4",
        downloadUrl: "/downloads/nrmlss.zip",
      },
      {
        id: "deadspace",
        name: "Deadspace",
        videoUrl: "/videos/deadspace.mp4",
        downloadUrl: "/downloads/deadspace.zip",
      },
      {
        id: "portfolio",
        name: "Portfolio Showcase",
        videoUrl: "/videos/portfolio.mp4",
        downloadUrl: "/downloads/portfolio.zip",
      },
      {
        id: "music-and-dance",
        name: "Music and Dance",
        videoUrl: "/videos/music-and-dance.mp4",
        downloadUrl: "/downloads/music-and-dance.zip",
      },
    ],
    bonusTemplates: [
      {
        id: "hero-master",
        name: "Hero Sections Master Pack",
        videoUrl: "/videos/hero-master.mp4",
        downloadUrl: "/downloads/hero-master.zip",
      },
      {
        id: "cta-pack",
        name: "CTA & Conversion Sections",
        videoUrl: "/videos/cta-pack.mp4",
        downloadUrl: "/downloads/cta-pack.zip",
      },
      {
        id: "motion-presets",
        name: "GSAP & Motion Presets",
        videoUrl: "/videos/motion-presets.mp4",
        downloadUrl: "/downloads/motion-presets.zip",
      },
    ],
  },
];
